spring:
  datasource:
    url: jdbc:postgresql://db.zgaqgfoyjnvenkapsufn.supabase.co:5432/postgres?user=${USER}&password=${PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

